# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [2]:
# Ejercicios 1–5

# 1
a = np.array([1, 2, 3, 4])
print("1)", np.all(a != 0))

# 2
a = np.array([0, 0, 2, 0])
print("2)", np.any(a != 0))

# 3
a = np.array([1, 2, np.nan, np.inf])
print("3) contiene inf:", np.isinf(a).any(), "| contiene NaN:", np.isnan(a).any())

# 4
a = np.array([1, 2, np.inf])
print("4)", np.isinf(a).any())

# 5
a = np.array([1, np.nan, 3])
print("5)", np.isnan(a).any())

1) True
2) True
3) contiene inf: True | contiene NaN: True
4) True
5) True


In [3]:
# Ejercicios 6–10

# 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
print("6) a:", a)
print("   b:", b)
print("   a > b:", a > b)
print("   a >= b:", a >= b)
print("   a < b:", a < b)
print("   a <= b:", a <= b)

# 7
a = np.array([1, 7, 13, 105])
print("7) nbytes:", a.nbytes)

# 8
print("8) ceros:", np.zeros(10, dtype=int))
print("   unos:", np.ones(10, dtype=int))
print("   cincos:", np.full(10, 5, dtype=int))

# 9
print("9)", np.arange(30, 71))

# 10
print("10)", np.arange(30, 71, 2))

6) a: [1 3 5]
   b: [2 3 4]
   a > b: [False False  True]
   a >= b: [False  True  True]
   a < b: [ True False False]
   a <= b: [ True  True False]
7) nbytes: 32
8) ceros: [0 0 0 0 0 0 0 0 0 0]
   unos: [1 1 1 1 1 1 1 1 1 1]
   cincos: [5 5 5 5 5 5 5 5 5 5]
9) [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
10) [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [4]:
# Ejercicios 11–15

# 11
print("11)\n", np.eye(3, dtype=int))

# 12
print("12)", np.random.random())

# 13
print("13)", np.random.randn(15))

# 14
a = np.arange(15, 56)
print("14)", a[1:-1])

# 15
print("15)", np.linspace(5, 50, 10) )

11)
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
12) 0.4582160500216995
13) [-1.50040463  1.32231456  0.33090544  0.44697991  1.49583411 -0.94127529
 -0.096385   -0.58319273 -1.05946117  0.02376017  0.24834945 -2.18218638
 -1.18164685 -0.48375022 -1.56706581]
14) [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
15) [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [5]:
# Ejercicios 16–20

# 16
v = np.arange(0, 21)
v2 = v.copy()
v2[(v2 >= 9) & (v2 <= 15)] *= -1
print("16) original:", v)
print("    cambiado:", v2)

# 17
a = np.array([1, 2, 3])
print("17)", a.tolist())

# 18
l = [1, 2, 3]
print("18)", np.array(l))

# 19
m = np.array([[1, 2], [3, 4]])
pares = (m % 2 == 0)
print("19) m:\n", m)
print("    pares:\n", pares)

# 20
m = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m.shape
print("20) shape:", m.shape, "| filas:", filas, "| columnas:", columnas)

16) original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
    cambiado: [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]
17) [1, 2, 3]
18) [1 2 3]
19) m:
 [[1 2]
 [3 4]]
    pares:
 [[False  True]
 [False  True]]
20) shape: (2, 3) | filas: 2 | columnas: 3
